feat: add trigger module
gelatodigital/automate pull request #107
Opened 2023-07-27 12:07 UTC by mkykadir

2023-07-28 08:53 UTC, brandonchuah reviewed
@mkykadir Do you think it is necessary to store the `TriggerType` & `TriggerConfig` on-chain? 

Could we do something similar to `Web3FunctionModule` where the w3f hash & arguments are emitted in [moduleData](https://github.com/gelatodigital/automate/blob/0fab4305f092f8ff2ba675e6cae87591926039f5/contracts/Automate.sol#L291) as we don't do any validation with the stored TriggerType & TriggerConfig values.

2023-07-31 05:44 UTC, mkykadir commented
@brandonchuah I agree but there is this validation that needs to be done for time interval triggering

```
            uint128 actualStart = uint256(start) > block.timestamp
                ? start
                : uint128(block.timestamp);
```

should I add this to the encoding function?

2023-07-31 06:33 UTC, brandonchuah commented
@mkykadir do you think we could skip this validation? On our backend, we start checking immediately if `start < Date.now()`

2023-07-31 07:36 UTC, brandonchuah reviewed
A question. Will `TRIGGER` module be strictly necessary when `WEB3_FUNCTION` module is enabled. If so, it wil

2023-07-31 07:36 UTC, brandonchuah commented on contracts/taskModules/TriggerModule.sol
> +        return abi.encode(_start, _interval);
```suggestion
        bytes memory triggerConfig = abi.encode(_start, _interval);

        return abi.encode(LibDataTypes.TriggerType.TIME, triggerConfig);
```

2023-07-31 07:36 UTC, brandonchuah commented on contracts/taskModules/TriggerModule.sol
> +        return abi.encode(_expression);
```suggestion
        bytes memory triggerConfig = abi.encode(_expression);

        return abi.encode(LibDataTypes.TriggerType.CRON, triggerConfig);
```

2023-07-31 07:36 UTC, brandonchuah commented on contracts/taskModules/TriggerModule.sol
> +import {LibEvents} from "../libraries/LibEvents.sol";
```suggestion
```

2023-07-31 07:36 UTC, brandonchuah commented on contracts/libraries/LibDataTypes.sol
> +        TRIGGER
Will `TRIGGER` module be strictly necessary when `WEB3_FUNCTION` module is enabled? If so, we might need to enforce it here: https://github.com/gelatodigital/automate/blob/0fab4305f092f8ff2ba675e6cae87591926039f5/contracts/libraries/LibTaskModule.sol#L287-L292

2023-07-31 07:48 UTC, mkykadir commented
> A question. Will `TRIGGER` module be strictly necessary when `WEB3_FUNCTION` module is enabled. If so, we might need to enforce it here:
> 
> https://github.com/gelatodigital/automate/blob/0fab4305f092f8ff2ba675e6cae87591926039f5/contracts/libraries/LibTaskModule.sol#L287-L292

According to the task description, Automate will have this as well
https://gelatonetwork.atlassian.net/browse/GN-3734

2023-08-09 09:26 UTC, goums requested changes

2023-08-10 09:27 UTC, mkykadir commented on test/utils/modules.ts
> +};
Since there is nothing specific going on for this module, should I replace TIME module usages to this?

2023-08-10 09:52 UTC, goums commented on test/utils/modules.ts
> +};
Time module need to keep it's full test coverage for now, as it has on chain state update.
But you can add a Trigger module in one test suite just to ensure it's usage is covered, even if by this I mean just verfying that the task creation is working fine, and the event is emitting decodable module args properly

2023-08-22 06:55 UTC, goums approved these changes

2023-09-04 03:08 UTC, merged